### ISSUE TITLE
Missing Items: Medical

### ISSUE THREAD

**Issue by Lorgenz** [Gurgstation/Gurgstation#108]
**Is your feature request related to a problem? Please describe.**
There are items missing that lead to a lower quality of life vs the previous tether map.

**Describe the solution you'd like**
Please include a nutrient/protein/milk dispenser in the chem lab, The normal beaker of cryoxydone next to the cryo cell. Add an additional cryo cell perhaps. change the number of biomass vials from 1 to 4 (people are vorny)

**Describe alternatives you've considered**
For some of these, I'm not aware of an alternative. while making things like extra biomass during a vorny shift could be a neat thing it gets in the way of one of the primary points of the server, hindering it.

**Additional context**
we have two normal chem dispensers and two chem masters but no animal product dispenser this is something that seems rather important. more biomass leaves less resistance to vornyness.

**Comment by Smdytb1** [comment]
no additional cryo cell but everything else is is added, doubled the cryo beaker amount however just for sanity purposes (psst. making extra cloneoxadone for synthmeat)
