### ISSUE TITLE
[BUG] The interior airlock doors to the mining shuttle start closed and cannot be opened from the station's side by miners.

### ISSUE THREAD

**Issue by Silverwing525** [Gurgstation/Gurgstation#109]
The title says it all.  Miners cannot access the mining shuttle without admin intervention due to the airlock doors starting closed and being unable to be opened from the station's side.

The door starts cycling to interior when either the button is pressed or the door is pushed against.

Button press does nothing and pressing against the door turns on the access denied lights.

#### Steps to reproduce
- (Step 1)  Attempt to open doors via touch.
- (Step 2)  Doors give access denied lights.
- Step 3, attempt to open via interior access button
- Step four, nothing happens because button does do anything.
- Step five, attempt to hack door without gloves
- Step six get electrocuted for being an idiot. 
- Step seven.  Realize this is an issue that should be reported.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Smdytb1** [comment]
fixed in a commit to master. should work now.
