### ISSUE TITLE
Mining Shuttle Helm controls deny access to Miners.[BUG]

### ISSUE THREAD

**Issue by Silverwing525** [Gurgstation/Gurgstation#110]
The mining shuttle's helm controls deny access to the miners, making it so that a pilot is required for miners to actually do their job.  This is a little ridiculous as Miners should have enough know how to figure out how to get to a mining asteroid without an escort.

The helm console should bring up the shuttle controls window.

Access Denied message pops.

#### Steps to reproduce
- (Step 1)  Attempt to access Mining shuttle controls.
- (Step 2)  Get denied access because you are a miner and not a pilot.
- Step 3.  Attempt to rejoin as a pilot.
-Step 4.  Realize that pilots cannot access mining.
-Step 5.  Realize that mining is impossible till proper permissions are worked out.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Smdytb1** [comment]
fixed in recent commit
