### ISSUE TITLE
Lower robotics bay door switch only opens UPPER robotics door door[BUG]

### ISSUE THREAD

**Issue by Silverwing525** [Gurgstation/Gurgstation#112]
For some reason the switch by the lower robotics bay door only opens the upper door.
![Untitled](https://user-images.githubusercontent.com/50423734/132970545-031c3e10-c134-43eb-966f-c0f73728393a.png)
![Untitled2](https://user-images.githubusercontent.com/50423734/132970549-9edb9c3d-79cd-4f05-a08f-843703100815.png)

#### Steps to reproduce
- (Step 1)
- (Step 2)
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 

#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Smdytb1** [comment]
fixed in recent commit.
