### ISSUE TITLE
Invisible Cockroach

### ISSUE THREAD

**Issue by AmethystTheSergal** [Gurgstation/Gurgstation#163]
Sprite for the roaches are missing. Only real way to see them is either accidently step on one, or right click any individual tile.

![Roach](https://user-images.githubusercontent.com/52103820/164948955-3ad063b3-d12c-40d2-9c29-21e91e202166.PNG)

**Comment by GremlingSS** [comment]
Oh, forgot to label this as fixed.

Funnily, no codebase has a cockroach sprite in their files, the closest is TGStation, who has a glockroach. :')
I added it though. Found a wae

**Comment by GremlingSS** [comment]
Fixed with #161
