### ISSUE TITLE
Various Minor Map Issues [MAPPING] 

### ISSUE THREAD

**Issue by amenitykitten** [Gurgstation/Gurgstation#185]
Just a few very minor issues noticed while wondering around.
**Cafe:** 
- The new cafe has no sink, making the wrong drink will get annoying, since you can't pour it out without a sink.
**Kitchen:** 
- The Chef has no Universal Enzyme. This is required for like, a solid half of the foods.
- The "Kitchen Gate" button on the north side of the counters opens and lowers the gate correctly. However, the one on the right hand side near the shutters, opens the shutters, and the "Kitchen Shutters" button instead opens the Gate on that side. This is confusing.
- [Nonissue] The Kitchen counter bulges out, when pulling it in one tile would make it seamlessly be able to have it's shutters closed, and look more consistent with the rest of the bar around it.

I'll probably add more to this if I notice more.

**Comment by Dropshotz** [comment]
Chef has universal enzyme in the top right corner. Added an extra in the kitchen cabinet just in case.
