### ISSUE TITLE
aaaaugh, floating cameras and possibly more[MAPPING] 

### ISSUE THREAD

**Issue by Dropshotz** [Gurgstation/Gurgstation#191]
Floating camera in front of bar.
Security EVA camera misaligned

**Comment by amenitykitten** [comment]
the hop's hat should be named the 'Head of Personnel's Hat' and not the 'crew resource hat', and while this isn't a bug nor an incorrect anything, it just feels absolutely more accurate this way because the HOP's cloak and Beret are labelled like that

**Comment by MisterGrimm** [comment]
> Pilot and Exploration shouldn't be Civilian, as Exploration into new lands should be overseen purely by the Research Director. Move Pilot into Science Jobs. The Head of Personnel's job is managing crew pay and crew jobs and access, along with ensuring the Cargo and Service departments are running smoothly, they should not have Exploration crew Comms. There are more arguments for the CMO and Paramedics having this communication line than the Head of Personnel.

Being a pilot is not a science based job, as exploration at this moment does not exist anymore. A pilots job is only to pilot, not to explore. He can pilot for a crew that wants to explore, but the job description itself is not exploration. In fact, the pilot doesn't even get a exploration channel.

**Comment by Dropshotz** [comment]
fixed most issues. I will not get involved with the validity of pilot/explo going either here or there. apologies.
