### ISSUE TITLE
[MAPPING] Map issues

### ISSUE THREAD

**Issue by Dropshotz** [Gurgstation/Gurgstation#206]
Xenobio misses a vending machine
1 or 2 more laptop vendors needed

Feel free to add more in comments

**Comment by Dropshotz** [comment]
add spes cleaner to xenobio

**Comment by MisterGrimm** [comment]
![image](https://user-images.githubusercontent.com/26284899/230668310-7c77b30c-828a-4b57-8cb8-2c516d1ce008.png)
Second floor, northwest of elevator. Spot is supposed to have a T section disposal pipe here.

**Comment by Dropshotz** [comment]
Some genius decided the tiny fan tile in the mining shuttle to be airless.

**Comment by Dropshotz** [comment]
Engineering is not apubblic hallway, remove access.
Why the FUCK is the engine room not engine room access?

**Comment by Dropshotz** [comment]
broken pipe in the libraryyyyy
