### ISSUE TITLE
[FEAT] Merge new replicator from Vorestation.

### ISSUE THREAD

**Issue by amenitykitten** [Gurgstation/Gurgstation#212]
Definitely low priority, just a request.

The replicator was updated by Diana (Cameron653) like, two months ago into a machine that uses TF Code and allows players to be transformed instead of just objects.
It's probably got a few issues (and would need to be checked out both before and after merging), but TF items are nice to have added, even if it's just an updated archaeology find.

**Comment by Dropshotz** [comment]
Leaning slightly towards yes.

**Comment by MisterGrimm** [comment]
The replicator/vore is already in the code. The machine was updated 10 months ago as of this post.

**Comment by Dropshotz** [comment]
this can be closed no?
