### ISSUE TITLE
New map global issues

### ISSUE THREAD

**Issue by Tasald** [Gurgstation/Gurgstation#80]
Excursion shuttle is not linked to it's engines or sensors

Airlocks are fuked all over, they don't cycle properly

Exploration really could use another point vendor machine in it's area, not just the ship
Could also use more the 2 parachutes

Sentries in the gateway room need to be set to station access allowed or something, so they are not just shooting anyone whos not in a command role or what ever they're set to.

The escape shuttle area is not wired properly

**Comment by GremlingSS** [comment]
oki so the airlocks have been patched but the serber didn't update with it apparently so idk if there's any sneaky ones which I hadn't fixed prior to the server deployment.

I just fixed the excursion shuttle i thinksies, gonna test after I check on a few more things you said, thanks tho! I got the PR doing all the changes at #79 so ye.

Speedydeernoises.gifpeg

**Comment by GremlingSS** [comment]
Where are these parachutes btw? trying to look for them on the map can't find them anywhere heck

**Comment by Tasald** [comment]
the feild medic lockers should probably be in the same room as their hardsuits, currently their lockers are in the exploration medical area and their suits are with the regular exploration lockers.

there's also alota wasted space in the exploration suit up area, it's a really long room but with barely anything in it.

**Comment by Tasald** [comment]
hmm i think the hos' hardsuit is missing from their suit storage display case

**Comment by Tasald** [comment]
also some of the away maps have broken turf tiles
like the desert gold min or abandoned farmstead

**Comment by Tasald** [comment]
i wouldn't be opposed to swapping the prep rooms for exploration with the pathfinder officer, then give the pathfinder their own bedroom like how the warden has their own bedroom >w>

**Comment by GremlingSS** [comment]
yea they do

**Comment by GremlingSS** [comment]
personally the suggestions here are big changes to the sillouhette of the station which I dont wanna fuck with, I aint a mapper I'm just a nerd.

**Comment by GremlingSS** [comment]
but I do agree

**Comment by Tasald** [comment]
ah well i guess it would change the map a bit, but i can't find the rd's sleeping area...and the captians sleeping area is like the second worst one on the map compared to the other officers

**Comment by GremlingSS** [comment]
xD yea

**Comment by GremlingSS** [comment]
puny deer brain thought this was a sleeping room

**Comment by GremlingSS** [comment]
![image](https://user-images.githubusercontent.com/68038883/131590795-bd6901f2-33b0-48ee-ac16-503282e40797.png)

**Comment by Tasald** [comment]
kek
