### ISSUE TITLE
[BUG] Janitorial closet needs some private TLC

### ISSUE THREAD

**Issue by GremlingSS** [Gurgstation/Gurgstation#97]
#### Brief description of the bug
Is dark in there, the janitorial carts need mop buckets, ass needs blastin, that bout it.
![image](https://user-images.githubusercontent.com/68038883/132072185-931f5c81-8d06-4987-ad79-762ba7a1cd61.png)

**Comment by Smdytb1** [comment]
this was fixed without closing, closing.
